Repository lake-county-tech-meetup/website, pull requests merged in 2019-10, with the labels that each got.

#4 Package & Version bump
  package.json
  yarn.lock
Labels: Status: Complete, enhancement, updates

#15 updates
  package.json
  yarn.lock
Labels: optimization, updates

#17 fixed accessibility with form in contact us
  src/pages/contact-us.js
Labels: Priority: Critical, accessibility

#21 Create code-of-conduct.md
  code-of-conduct.md
Labels: documentation, hacktoberfest

#22 Add base style & restructure layout files
  database/static/frontpage.json
  gatsby-config.js
  package.json
  postcss.config.js
  src/assets/images/logo-circle.svg
  src/assets/images/logo-circle@512px.png
  src/assets/images/logo-illinois.svg
  src/assets/images/logo-illinois@512px.png
  src/assets/images/logo.svg
  src/assets/images/logo@512px.png
  src/assets/stylesheets/style.css
  src/assets/stylesheets/webfonts.css
  src/components/Footer.js
  src/components/Layouts/DefaultLayout.js
  src/components/Layouts/LayoutWrapper.js
  src/components/Layouts/index.js
  src/components/header.js
  src/components/layout.css
  src/hooks/useFetchJson.js
  src/pages/404.js
  src/pages/about-us.js
  src/pages/contact-us.js
  src/pages/index.js
  tailwind.config.js
  yarn.lock
Labels: Priority: High, Status: in-progress, hacktoberfest

#24 modified eslint and still fixing build pathing issue
  .eslintrc
  src/components/footer.js
  src/pages/404.js
  src/pages/index.js
Labels: bug

#29 Implement testing with Jest and React-testing-library
  package.json
  src/__tests__/components/Footer.test.js
  src/config/setupTests.js
  yarn.lock
Labels: Status: in-progress, Tests: Unit, hacktoberfest, question

#31 Add prettier to eslint config
  .eslintrc
  .prettierrc
  package.json
  src/pages/404.js
  yarn.lock
Labels: Status: in-progress, bug, hacktoberfest

#39 [WIP] Feature: events
  .eslintrc
  .gitignore
  .nvmrc
  .prettierrc
  README.md
  gatsby-config.js
  gatsby-node.js
  gatsby/createPages/createEventPages.js
  gatsby/createPages/index.js
  gatsby/createPages/paginateEvents.js
  gatsby/createSchemaCustomization/index.js
  gatsby/onCreateNode/index.js
  gatsby/onCreateWebpackConfig/index.js
  jest.config.js
  jsconfig.json
  package.json
  src/__tests__/components/Footer.test.js
  src/__tests__/components/Header.test.js
  src/components/EventCard.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Image.js
  src/components/Layouts/LayoutWrapper.js
  src/components/Link.js
  src/components/MapLink.js
  src/components/Pagination.js
  src/components/SEO.js
  src/config/siteConfig.js
  src/events/.keep
  src/events/meetup-november-2019.md.sample
  src/pages/404.js
  src/pages/about-us.js
  src/pages/contact-us.js
  src/pages/index.js
  src/templates/event.js
  src/templates/events.js
  yarn.lock
Labels: Priority: Moderate, Status: in-progress, code review
